Adapt 'platform variable:create' to changed syntax
ezsystems/ezplatform pull request #495
Opened 2020-01-19 19:28 UTC by reithor

Syntax in platform CLI according to:
[https://docs.platform.sh/tutorials/composer-auth.html#set-the-envcomposerauth-project-variable]

2020-05-20 06:23 UTC, lserwatka commented
@vidarl could you review this PR?

2020-05-20 08:05 UTC, vidarl requested changes

2020-05-20 08:05 UTC, vidarl commented on doc/platformsh/INSTALL.md
> +      `platform variable:update env:SYMONY_ENV --value 'dev'`.
I am a bit fuzzed by the use of `update` here.. We set the the SYMFONY_ENV in `.platform.app.yaml`. Have you confirmed that setting this command actually works? Honestly, I couldn't find in p.sh docs if environment variables defined in `.platform.app.yaml` has precedence over project/environment variables or not.

2020-05-27 21:08 UTC, reithor commented on doc/platformsh/INSTALL.md
> +      `platform variable:update env:SYMONY_ENV --value 'dev'`.
I have checked it - and it overrides the setting.
Syntax is slightly different though: 
```platform variable:update --value 'dev' env:SYMFONY_ENV```
 
But simply setting SYMFONY_ENV to dev won't work anyway  - in .platform.app.yaml we use composer install :
```composer install --no-dev --prefer-dist --no-progress --no-interaction --optimize-autoloader```
 so dev packages are not installed on p.sh by default

2020-05-28 07:05 UTC, vidarl commented on doc/platformsh/INSTALL.md
> +      `platform variable:update env:SYMONY_ENV --value 'dev'`.
yes, I know.. We had a comment about this in `.platform.app.yaml` earlier, but it was removed.
So, maybe add info about this in a  6.5 bullet ?

2023-02-22 17:42 UTC, closed without merging