Downgraded "doctrine/dbal" to "2.10.4"
ezsystems/ezplatform pull request #600
Opened 2020-10-02 11:40 UTC by adamwojs

> JIRA: -

#### Description

Downgraded "doctrine/dbal" to "2.10.4" to unblock CI on 1.13 branch: 

```
install_app_1_1a889336cc0b | > Incenteev\ParameterHandler\ScriptHandler::buildParameters
install_app_1_1a889336cc0b | Creating the "app/config/parameters.yml" file
install_app_1_1a889336cc0b | > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
install_app_1_1a889336cc0b | > eZ\Bundle\EzPublishCoreBundle\Composer\ScriptHandler::clearCache
install_app_1_1a889336cc0b | 
install_app_1_1a889336cc0b |                                                         
install_app_1_1a889336cc0b |   [Symfony\Component\Console\Exception\LogicException]  
install_app_1_1a889336cc0b |   An option named "connection" already exists.          
install_app_1_1a889336cc0b |                                                         
install_app_1_1a889336cc0b | 
install_app_1_1a889336cc0b | Script eZ\Bundle\EzPublishCoreBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception
install_app_1_1a889336cc0b | 
install_app_1_1a889336cc0b |                                                                              
install_app_1_1a889336cc0b |   [RuntimeException]                                                         
install_app_1_1a889336cc0b |   An error occurred when executing the "'cache:clear --no-warmup'" command:  
install_app_1_1a889336cc0b |                                                                              
install_app_1_1a889336cc0b |                                                                              
install_app_1_1a889336cc0b |                                                                              
install_app_1_1a889336cc0b |                                                                              
install_app_1_1a889336cc0b |                                                                              
install_app_1_1a889336cc0b |     [Symfony\Component\Console\Exception\LogicException]                     
install_app_1_1a889336cc0b |     An option named "connection" already exists.                             
install_app_1_1a889336cc0b |                                                                              
install_app_1_1a889336cc0b | 
install_app_1_1a889336cc0b | install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
```

Source build: https://travis-ci.org/github/ezsystems/ezplatform/jobs/731802629

#### Links:

*   doctrine/DoctrineBundle#1168

2020-10-02 12:00 UTC, ViniTou approved these changes

2020-10-02 12:01 UTC, micszo submitted a review, later dismissed

2020-10-02 12:21 UTC, Nattfarinn approved these changes

2020-10-02 12:37 UTC, alongosz requested changes

2020-10-02 12:37 UTC, alongosz commented on composer.json
> +        "doctrine/dbal": "2.10.4",
2.10.4 requires PHP ^7.2. You need to setup a conflict instead.

2020-10-02 13:22 UTC, adamwojs commented on composer.json
> +        "doctrine/dbal": "2.10.4",
Fixed in 5346989

2020-10-02 13:23 UTC, adamwojs commented
PR updated according to @alongosz code review suggestions. Please wait for CI results.

2020-10-02 14:06 UTC, alongosz approved these changes

2020-10-02 14:09 UTC, micszo approved these changes

2020-10-05 11:18 UTC, mnocon approved these changes

2020-10-05 11:25 UTC, merged