EZP-32040: Redesigned welcome page
ezsystems/ezplatform pull request #614
Opened 2020-10-16 12:38 UTC by ciastektk

https://jira.ez.no/browse/EZP-32040

![welcome page v2](https://user-images.githubusercontent.com/9850711/96259030-41aca080-0fbd-11eb-913b-83eca3f58070.png)

2020-10-16 12:41 UTC, adamwojs approved these changes

2020-10-16 12:58 UTC, lucasOsti approved these changes

2020-10-16 13:01 UTC, dew326 approved these changes

2020-10-18 18:49 UTC, GrabowskiM requested changes

2020-10-18 18:49 UTC, GrabowskiM commented on assets/images/conversation-chat-icon.svg
> +</svg>
Newline

2020-10-18 18:49 UTC, GrabowskiM commented on assets/images/file-text-info-icon.svg
> +</svg>
Newline

2020-10-18 18:49 UTC, GrabowskiM commented on assets/images/folder-icon.svg
> +    </g>
Newline

2020-10-19 09:46 UTC, merged