Adding fixed for IBX-5077
ezsystems/ezplatform pull request #690
Opened 2023-03-02 12:45 UTC by jwibexa

2023-03-02 13:46 UTC, micszo requested changes
Please add some minimal description.

Also please link to JIRA ticket in description.

2023-03-03 09:13 UTC, mnocon reviewed
Looking good, thanks! 🎉 

Please try to include meaningful commit messages as well - the title of this PR (`IBX-5077: Changed deprecated GitHub actions `) would be a great commit message .

I have one, hopefully small, request:
Can we sneak in two additional changes here to get rid of all deprecations?

I'd change:
`uses: actions/checkout@v2`
to
`uses: actions/checkout@v3`

This will get rid of:
```
Admin UI on Clean Platform / browser-tests
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

and second one:
`        runs-on: ubuntu-18.04`
to
`        runs-on: ubuntu-20.04`

To get rid of:
```
Browser tests: .github#L1
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
```

2023-03-03 11:08 UTC, mnocon approved these changes
Thank you! 🤩

2023-03-07 14:43 UTC, bogusez approved these changes

2023-03-08 08:32 UTC, tomaszszopinski approved these changes

2023-03-08 08:39 UTC, micszo approved these changes

2023-03-08 14:08 UTC, merged